-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for routes
create table routes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  start_name text not null,
  start_lat double precision not null,
  start_lng double precision not null,
  end_name text not null,
  end_lat double precision not null,
  end_lng double precision not null,
  price numeric not null,
  vehicle_type text not null check (vehicle_type in ('taxi', 'bus', 'ride', 'bajaj')),
  description text,
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for routes
alter table routes enable row level security;

create policy "Routes are viewable by everyone."
  on routes for select
  using ( true );

create policy "Authenticated users can insert routes."
  on routes for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update own routes."
  on routes for update
  using ( auth.uid() = user_id );

-- Create a table for route stops (waypoints)
create table stops (
  id bigint generated by default as identity primary key,
  route_id bigint references routes on delete cascade not null,
  name text,
  lat double precision not null,
  lng double precision not null,
  stop_order int not null
);

alter table stops enable row level security;

create policy "Stops are viewable by everyone."
  on stops for select
  using ( true );

create policy "Authenticated users can insert stops."
  on stops for insert
  with check ( auth.role() = 'authenticated' );

-- Create a table for reviews
create table reviews (
  id bigint generated by default as identity primary key,
  route_id bigint references routes on delete cascade not null,
  user_id uuid references auth.users not null,
  rating int not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table reviews enable row level security;

create policy "Reviews are viewable by everyone."
  on reviews for select
  using ( true );

create policy "Authenticated users can insert reviews."
  on reviews for insert
  with check ( auth.role() = 'authenticated' );
